
[functions.notify-admin-approval]
enabled = true
verify_jwt = false
import_map = "./functions/notify-admin-approval/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-admin-approval/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-admin-approval/*.html" ]

[functions.admin-pending-emails]
enabled = true
verify_jwt = false
import_map = "./functions/admin-pending-emails/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-pending-emails/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-pending-emails/*.html" ]

[functions.chat]
enabled = true
verify_jwt = false
import_map = "./functions/chat/deno.json"
entrypoint = "./functions/chat/index.ts"

[functions.insights-scan]
enabled = true
verify_jwt = false
import_map = "./functions/insights-scan/deno.json"
entrypoint = "./functions/insights-scan/index.ts"
